// <auto-generated />
namespace KoalaCode.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_fullName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_fullName));
        
        string IMigrationMetadata.Id
        {
            get { return "201509242131027_remove_fullName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
